doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true

    connections:
        default:
            # Connexion directe au conteneur Docker MongoDB
            server: 'mongodb://root:root@symfony_mongodb:27017'
            options:
                authSource: admin

    default_database: travel_guide_nosql

    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: attribute
                    dir: '%kernel.project_dir%/src/Document'
                    prefix: 'App\Document'

when@prod:
    doctrine_mongodb:
        auto_generate_proxy_classes: false
        auto_generate_hydrator_classes: false
        document_managers:
            default:
                metadata_cache_driver:
                    type: service
                    id: doctrine_mongodb.system_cache_pool

    framework:
        cache:
            pools:
                doctrine_mongodb.system_cache_pool:
                    adapter: cache.system
