# Dockerfile pour Symfony 8 + PHP 8.4 + Apache
FROM php:8.4-apache

# Installer dépendances système + PHP
RUN apt-get update && apt-get install -y \
    git unzip zip libicu-dev libzip-dev libpng-dev libonig-dev libxml2-dev \
    && docker-php-ext-install intl pdo pdo_mysql zip opcache \
    && rm -rf /var/lib/apt/lists/*

# Installer Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# DocumentRoot Symfony
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

# Copier config Apache personnalisée
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf

WORKDIR /var/www/html

# Créer dossiers Symfony + permissions
RUN mkdir -p var/cache var/log \
    && chown -R www-data:www-data var \
    && chmod -R 775 var

USER www-data

EXPOSE 80
